services:
  local-db:
    image: postgres:latest
    container_name: local-db
    environment:
      - POSTGRES_PASSWORD=local-db
    ports:
      - "5433:5432"



  prod-db:
    image: postgres:latest
    container_name: prod-db
    environment:
      - POSTGRES_PASSWORD=prod-db
    ports:
      - "5435:5432"
