spring.application.name=accounts

spring.datasource.url=jdbc:postgresql://loalhost:5433/accounts
spring.datasource.username=postgres
spring.datasource.password=local-db


spring.jpa.hibernate.ddl-auto=create-drop
server.servlet.context-path=/v1